/// <reference lib="webworker" />
import * as ort from 'onnxruntime-web/webgpu';
import ortWasmMjsUrl from 'onnxruntime-web/ort-wasm-simd-threaded.asyncify.mjs?url';
import ortWasmUrl from 'onnxruntime-web/ort-wasm-simd-threaded.asyncify.wasm?url';

ort.env.wasm.numThreads=1;ort.env.wasm.simd=true;ort.env.wasm.wasmPaths={mjs:ortWasmMjsUrl,wasm:ortWasmUrl};ort.env.webgpu.powerPreference='high-performance';ort.env.webgpu.forceFallbackAdapter=false;
ort.env.logLevel='warning';
const BASE='https://huggingface.co/haixin/timeline-studio-onnx-models/resolve/a201b681c8f96672b5c3f624e32d4dc932f150af/liveportrait-webgpu/';
const FILES={
 appearance:['liveportrait-appearance_feature_extractor.onnx'],
 motion:['liveportrait-motion-extractor.onnx.part-aa','liveportrait-motion-extractor.onnx.part-ab','liveportrait-motion-extractor.onnx.part-ac'],
 stitching:['liveportrait-stitching.onnx'],
 generator:['liveportrait-generator-preview-fp16.onnx.part-aa?v=5fdb50d2','liveportrait-generator-preview-fp16.onnx.part-ab?v=5fdb50d2','liveportrait-generator-preview-fp16.onnx.part-ac?v=5fdb50d2','liveportrait-generator-preview-fp16.onnx.part-ad?v=5fdb50d2','liveportrait-generator-preview-fp16.onnx.part-ae?v=5fdb50d2']
};
type Sessions={appearance:ort.InferenceSession;motion:ort.InferenceSession;stitching:ort.InferenceSession;generator:ort.InferenceSession};
let sessions:Sessions|null=null,feature:ort.Tensor|null=null,sourceMotion:Record<string,ort.Tensor>|null=null,sourceKp:Float32Array|null=null,initialDriver:Float32Array|null=null,busy=false;
const tensor=(data:Float32Array,dims:number[])=>new ort.Tensor('float32',data,dims);
function status(stage:string,progress:number,detail=''){postMessage({type:'status',stage,progress,detail})}
async function modelBytes(key:keyof typeof FILES){const cache=await caches.open('facemirror-liveportrait-v1');const parts:Uint8Array[]=[];let total=0;for(let i=0;i<FILES[key].length;i++){const file=FILES[key][i],url=BASE+file;let response=await cache.match(url);if(!response){response=await fetch(url);if(!response.ok)throw new Error(`Model download failed: ${response.status} ${file}`);await cache.put(url,response.clone())}const bytes=new Uint8Array(await response.arrayBuffer());parts.push(bytes);total+=bytes.length;status('Downloading neural models',8+Math.round(((i+1)/FILES[key].length)*12),key)}const out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out.buffer}
async function prepare(){if(sessions)return;if(!('gpu' in navigator))throw new Error('WebGPU is not available. Use current Chrome/Edge with hardware acceleration enabled.');status('Loading LivePortrait',3,'~326 MB on first use');const keys=(Object.keys(FILES) as (keyof typeof FILES)[]);const loaded:Partial<Sessions>={};for(let i=0;i<keys.length;i++){const key=keys[i];status('Loading LivePortrait',Math.round(5+i/keys.length*70),key);const model=await modelBytes(key);const provider=key==='generator'?{name:'webgpu',preferredLayout:'NHWC'}:'webgpu';const options:ort.InferenceSession.SessionOptions={executionProviders:[provider as never],graphOptimizationLevel:'all'};if(key==='appearance')(options as Record<string,unknown>).preferredOutputLocation={output:'gpu-buffer'};loaded[key]=await ort.InferenceSession.create(model,options)}sessions=loaded as Sessions;status('Neural engine ready',100,'WebGPU')}
async function preprocess(image:ImageBitmap){const size=Math.min(image.width,image.height),sx=(image.width-size)/2,sy=Math.max(0,(image.height-size)/2-size*.1);const c=new OffscreenCanvas(256,256),x=c.getContext('2d',{willReadFrequently:true})!;x.drawImage(image,sx,sy,size,size,0,0,256,256);image.close();const rgba=x.getImageData(0,0,256,256).data,plane=65536,chw=new Float32Array(plane*3);for(let i=0;i<plane;i++){chw[i]=rgba[i*4]/255;chw[plane+i]=rgba[i*4+1]/255;chw[plane*2+i]=rgba[i*4+2]/255}return tensor(chw,[1,3,256,256])}
function degree(data:ort.TypedTensor<'float32'>['data']){let max=-Infinity;for(const v of data)max=Math.max(max,Number(v));let sum=0,w=0;for(let i=0;i<data.length;i++){const v=Math.exp(Number(data[i])-max);sum+=v;w+=v*i}return w/sum*3-97.5}
function mm(a:Float32Array,b:Float32Array){const o=new Float32Array(9);for(let r=0;r<3;r++)for(let c=0;c<3;c++)o[r*3+c]=a[r*3]*b[c]+a[r*3+1]*b[3+c]+a[r*3+2]*b[6+c];return o}
function rotation(p:number,y:number,r:number){const X=p*Math.PI/180,Y=y*Math.PI/180,Z=r*Math.PI/180;const rx=new Float32Array([1,0,0,0,Math.cos(X),-Math.sin(X),0,Math.sin(X),Math.cos(X)]),ry=new Float32Array([Math.cos(Y),0,Math.sin(Y),0,1,0,-Math.sin(Y),0,Math.cos(Y)]),rz=new Float32Array([Math.cos(Z),-Math.sin(Z),0,Math.sin(Z),Math.cos(Z),0,0,0,1]);const v=mm(rz,mm(ry,rx));return new Float32Array([v[0],v[3],v[6],v[1],v[4],v[7],v[2],v[5],v[8]])}
function transform(m:Record<string,ort.Tensor>){const R=rotation(degree(m.pitch.data as Float32Array),degree(m.yaw.data as Float32Array),degree(m.roll.data as Float32Array)),out=new Float32Array(63),kp=m.kp.data as Float32Array,exp=m.exp.data as Float32Array,scale=Number(m.scale.data[0]),t=m.t.data;for(let p=0;p<21;p++){const o=p*3;for(let a=0;a<3;a++)out[o+a]=scale*(kp[o]*R[a]+kp[o+1]*R[3+a]+kp[o+2]*R[6+a]+exp[o+a]);out[o]+=Number(t[0]);out[o+1]+=Number(t[1])}return out}
async function setSource(bitmap:ImageBitmap){await prepare();status('Encoding source identity',92);feature?.dispose();if(sourceMotion)Object.values(sourceMotion).forEach(t=>t.dispose());const input=await preprocess(bitmap);feature=(await sessions!.appearance.run({img:input})).output;sourceMotion=await sessions!.motion.run({img:input});sourceKp=transform(sourceMotion);initialDriver=null;input.dispose();status('Neural mirror ready',100,'Move in front of the camera');postMessage({type:'sourceReady'})}
function outputBitmap(output:ort.Tensor){const data=output.data as Float32Array,[,,,W]=output.dims,H=output.dims[2],plane=W*H,rgba=new Uint8ClampedArray(plane*4);for(let i=0;i<plane;i++){rgba[i*4]=Math.max(0,Math.min(255,Math.round(data[i]*255)));rgba[i*4+1]=Math.max(0,Math.min(255,Math.round(data[plane+i]*255)));rgba[i*4+2]=Math.max(0,Math.min(255,Math.round(data[plane*2+i]*255)));rgba[i*4+3]=255}const c=new OffscreenCanvas(W,H);c.getContext('2d')!.putImageData(new ImageData(rgba,W,H),0,0);return c.transferToImageBitmap()}
async function render(bitmap:ImageBitmap){if(busy||!sessions||!feature||!sourceKp){bitmap.close();return}busy=true;const started=performance.now();try{const input=await preprocess(bitmap),driverMotion=await sessions.motion.run({img:input}),driver=transform(driverMotion);input.dispose();if(!initialDriver)initialDriver=new Float32Array(driver);const target=new Float32Array(63);for(let i=0;i<63;i++)target[i]=sourceKp[i]+(driver[i]-initialDriver[i]);const stitchInput=new Float32Array(126);stitchInput.set(sourceKp);stitchInput.set(target,63);const stitch=await sessions.stitching.run({input:tensor(stitchInput,[1,126])});for(let i=0;i<63;i++)target[i]+=Number(stitch.output.data[i]);for(let p=0;p<21;p++){target[p*3]+=Number(stitch.output.data[63]);target[p*3+1]+=Number(stitch.output.data[64])}const generated=await sessions.generator.run({feature_3d:feature,kp_source:tensor(sourceKp,[1,21,3]),kp_driving:tensor(target,[1,21,3])});const frame=outputBitmap(generated.out);Object.values(driverMotion).forEach(t=>t.dispose());Object.values(stitch).forEach(t=>t.dispose());Object.values(generated).forEach(t=>t.dispose());postMessage({type:'frame',frame,ms:Math.round(performance.now()-started)},[frame])}finally{busy=false}}
self.onmessage=(e:MessageEvent)=>{const run=e.data.type==='prepare'?prepare():e.data.type==='source'?setSource(e.data.bitmap):e.data.type==='frame'?render(e.data.bitmap):Promise.resolve();run.catch(error=>postMessage({type:'error',message:error instanceof Error?error.message:String(error)}))};
