import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowLeft, Camera, Check, ChevronRight, CircleDot, CircleHelp, Frown, Gauge, Grid2X2, ImagePlus, Minimize2, MonitorUp, Pause, Play, Settings, ShieldCheck, SlidersHorizontal, Smile, Sparkles, Upload, Video, X, Zap } from 'lucide-react';
import { categories, demos, getDemo, type Demo } from './catalog';
import { useFaceEngine, type EngineState, type Point } from './useFaceEngine';
import PortraitCanvas from './PortraitCanvas';
import { useLivePortrait, type NeuralState } from './useLivePortrait';
import { useGpuPortrait } from './useGpuPortrait';
import './styles.css';

type Prefs={sensitivity:number;smoothing:number;pose:number;mouth:number;brightness:number;contrast:number;saturation:number;mesh:boolean;mirror:boolean;identity:boolean;quality:string;reduceMotion:boolean};
const defaults:Prefs={sensitivity:75,smoothing:68,pose:55,mouth:72,brightness:100,contrast:100,saturation:100,mesh:true,mirror:true,identity:true,quality:'High',reduceMotion:false};
const go=(path:string)=>{location.hash=path};
function useRoute(){const read=()=>location.hash.replace(/^#\/?/,'')||'home';const [route,setRoute]=useState(read);useEffect(()=>{const f=()=>setRoute(read());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return route;}

function Brand(){return <button className="brand" onClick={()=>go('home')}><span className="brand-mark"><Sparkles/></span><span>FaceMirror<small>STUDIO</small></span></button>}
function StatusPill({state}:{state:EngineState}){return <div className={'status-pill '+state.status}><i/>{state.running?`${state.fps || '—'} FPS · LOCAL`:state.status==='loading'?'LOADING MODEL':'CAMERA OFF'}</div>}

function Header({state,onSettings}:{state:EngineState;onSettings:()=>void}){return <header><Brand/><nav><button className="nav-active" onClick={()=>go('home')}><Grid2X2/>Experiments</button><button onClick={()=>go('pipeline')}><Activity/>Pipeline</button></nav><div className="head-actions"><StatusPill state={state}/><button className="icon-btn" onClick={onSettings} aria-label="Settings"><Settings/></button></div></header>}

function Home({open}:{open:(d:Demo)=>void}){const [filter,setFilter]=useState('All');return <main className="home">
  <section className="hero"><div><span className="kicker"><i/> LOCAL-FIRST CREATIVE AI LAB</span><h1>Your face.<br/><em>Every possibility.</em></h1><p>Explore landmark tracking, portrait motion, speech dynamics, mouth rendering, and diffusion concepts—through one real-time creative workspace.</p><div className="hero-actions"><button className="primary" onClick={()=>location.href='./puppet.html'}><Play/>Open instant mirror</button><button className="secondary" onClick={()=>go('pipeline')}><Activity/>View full pipeline</button></div><div className="trust"><span><ShieldCheck/>Runs on device</span><span><Zap/>Real-time tracking</span><span><Check/>No uploads</span></div></div><div className="orb"><div className="orb-ring r1"/><div className="orb-ring r2"/><div className="face-glyph"><Sparkles/></div><span className="orbit-dot d1"/><span className="orbit-dot d2"/></div></section>
  <section className="library"><div className="section-title"><div><span className="eyebrow">EXPERIMENT LIBRARY</span><h2>Choose a workspace</h2></div><span>{demos.length} interactive demos</span></div>
  <div className="filters"><button className={filter==='All'?'active':''} onClick={()=>setFilter('All')}>All</button>{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div>
  <div className="card-grid">{demos.filter(d=>filter==='All'||d.category===filter).map((d,i)=><article className="demo-card" key={d.slug} style={{'--accent':d.accent,'--delay':`${i*20}ms`} as React.CSSProperties} onClick={()=>d.href?location.href=d.href:open(d)}><div className="card-top"><span className="demo-icon"><d.icon/></span><span className="live-dot">INTERACTIVE</span></div><span className="card-eyebrow">{d.eyebrow}</span><h3>{d.title}</h3><p>{d.description}</p><div className="tags">{d.capabilities.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><button>Open workspace <ChevronRight/></button></article>)}</div></section>
</main>}

function MeshOverlay({state,show}:{state:EngineState;show:boolean}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current,p=state.landmarks;if(!c||!p||!show)return;const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d')!;x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.fillStyle='rgba(103,232,249,.85)';const subset=[...Array(468)].filter((_,i)=>i%3===0);subset.forEach(i=>{if(!p[i])return;x.beginPath();x.arc((1-p[i].x)*w,p[i].y*h,1.15,0,7);x.fill()});},[state.landmarks,show]);return <canvas ref={ref} className="mesh-canvas"/>}

type Expression='live'|'smile'|'frown'|'o';
function PortraitStage({src,state,prefs,demo,expression,setExpression,detectStill,onCanvas,neural}:{src:string;state:EngineState;prefs:Prefs;demo:Demo;expression:Expression;setExpression:(e:Expression)=>void;detectStill:(img:HTMLImageElement)=>Promise<Point[]|null>;onCanvas:(c:HTMLCanvasElement|null)=>void;neural:NeuralState}){const neuralActive=Boolean(neural.frame)&&neural.status!=='error';return <div className="portrait-stage" style={{'--accent':demo.accent} as React.CSSProperties}>
 <div className="stage-grid"/><PortraitCanvas src={src} state={state} prefs={prefs} demo={demo} expression={expression} onExpression={setExpression} detectStill={detectStill} onCanvas={onCanvas} neuralFrame={neural.frame} neuralActive={neuralActive}/>
 {!state.running&&expression==='live'&&<div className="stage-prompt"><span><Camera/></span><h3>Real neural mirror</h3><p>Start to load LivePortrait WebGPU and drive this photo.</p></div>}
 {neural.status==='loading'&&<div className="neural-loader"><Sparkles/><b>{neural.detail}</b><i><em style={{width:`${neural.progress}%`}}/></i><small>{neural.progress}% · first load is approximately 326 MB and is cached</small></div>}
 {(neural.status==='error'||neural.status==='unsupported')&&<div className="neural-error"><b>Neural renderer error</b><span>{neural.detail}</span></div>}
 {state.status==='error'&&<div className="neural-error"><b>Camera / landmark engine error</b><span>{state.error}</span></div>}
 <div className="stage-badges"><span><ShieldCheck/>{state.landmarks?`${state.landmarks.length} LIVE LANDMARKS`:(neuralActive?'LIVEPORTRAIT ACTIVE':'SOURCE LANDMARKS')}</span><span><Zap/>{neural.status==='running'?`${neural.inferenceMs} MS`:neural.status.toUpperCase()}</span></div>
 </div>}

function SignalPanel({state,demo}:{state:EngineState;demo:Demo}){const s=state.signals;const vals=[['Jaw open',s.jawOpen],['Smile',s.smile],['Left blink',s.blinkLeft],['Right blink',s.blinkRight],['Brow raise',s.brow],['Head yaw',Math.abs(s.yaw)]];return <aside className="signals"><div className="panel-title"><span><Activity/>Live signals</span><small>{state.landmarks?'FACE FOUND':'WAITING'}</small></div>{vals.map(([n,v])=><div className="meter" key={n as string}><div><span>{n}</span><b>{Math.round((v as number)*100)}%</b></div><i><em style={{width:`${(v as number)*100}%`,background:demo.accent}}/></i></div>)}<div className="model-card"><span>ACTIVE ENGINE</span><b>MediaPipe Face Mesh</b><small>468 landmarks · WASM · local</small></div></aside>}

function Workspace({demo,state,videoRef,start,stop,detectStill,prefs,setPrefs,onSettings}:{demo:Demo;state:EngineState;videoRef:React.RefObject<HTMLVideoElement>;start:()=>Promise<void>;stop:()=>void;detectStill:(img:HTMLImageElement)=>Promise<Point[]|null>;prefs:Prefs;setPrefs:(p:Prefs)=>void;onSettings:()=>void}){const [source,setSource]=useState('/demo-portrait.jpg');const [cameraSmall,setCameraSmall]=useState(false);const [expression,setExpression]=useState<Expression>('live');const [recording,setRecording]=useState(false);const canvas=useRef<HTMLCanvasElement|null>(null);const recorder=useRef<MediaRecorder|null>(null);const neural=useLivePortrait(videoRef);const gpu=useGpuPortrait(videoRef);const [renderer,setRenderer]=useState<'gpu'|'browser'>('gpu');const activeNeural=renderer==='gpu'?gpu.state:neural.state;const onCanvas=useCallback((c:HTMLCanvasElement|null)=>{canvas.current=c},[]);const startMirror=async()=>{setExpression('live');await start();try{await gpu.start(source);setRenderer('gpu')}catch{setRenderer('browser');await neural.start(source)}};const stopMirror=()=>{gpu.stop();neural.stop();stop()};const upload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){const url=URL.createObjectURL(f);setSource(url);setExpression('live');if(state.running){if(renderer==='gpu')gpu.start(url).catch(()=>{setRenderer('browser');neural.start(url)});else neural.loadSource(url)}}};const download=(blob:Blob,name:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};const photo=()=>canvas.current?.toBlob(b=>b&&download(b,`facemirror-${Date.now()}.png`),'image/png');const record=()=>{if(recording){recorder.current?.stop();return}const c=canvas.current;if(!c)return;const chunks:Blob[]=[];const r=new MediaRecorder(c.captureStream(30),{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'});r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{download(new Blob(chunks,{type:'video/webm'}),`facemirror-${Date.now()}.webm`);setRecording(false)};r.start(500);recorder.current=r;setRecording(true)};return <main className="workspace" style={{'--accent':demo.accent} as React.CSSProperties}>
 <div className="crumb"><button onClick={()=>go('home')}><ArrowLeft/>Library</button><i/> {demo.category} <i/> <b>{demo.title}</b></div>
 <div className="work-head"><div><span className="eyebrow">{demo.eyebrow}</span><h1>{demo.title}</h1><p>{demo.description}</p></div><div className="work-actions"><label className="secondary upload"><Upload/>Choose portrait<input type="file" accept="image/*" onChange={upload}/></label><button className="icon-btn" onClick={onSettings}><SlidersHorizontal/></button></div></div>
 {demo.note&&<div className="honesty"><CircleHelp/><span><b>Demo scope</b>{demo.note}</span></div>}
 <div className="expression-tools"><span>CLICK-TO-POSE LANDMARKS</span><button className={expression==='live'?'active':''} onClick={()=>setExpression('live')}><Activity/>Live</button><button className={expression==='smile'?'active':''} onClick={()=>setExpression('smile')}><Smile/>Smile</button><button className={expression==='frown'?'active':''} onClick={()=>setExpression('frown')}><Frown/>Frown</button><button className={expression==='o'?'active':''} onClick={()=>setExpression('o')}><CircleDot/>O mouth</button><label className="landmark-check"><input type="checkbox" checked={prefs.mesh} onChange={e=>setPrefs({...prefs,mesh:e.target.checked})}/><span>Face landmarks</span></label><small>Click the portrait to cycle poses</small></div>
 <div className="studio-layout"><section className="main-view"><div className="view-bar"><div><i className={state.running?'on':''}/><span>TRIANGULATED PORTRAIT OUTPUT</span></div><div><span>{prefs.quality.toUpperCase()}</span><span>{state.fps||0} FPS</span></div></div><PortraitStage src={source} state={state} prefs={prefs} demo={demo} expression={expression} setExpression={setExpression} detectStill={detectStill} onCanvas={onCanvas} neural={activeNeural}/><div className="transport"><button className={state.running?'danger':'primary'} onClick={state.running?stopMirror:startMirror}>{state.running?<><Pause/>Stop camera</>:<><Play/>Start neural mirror</>}</button><button className="secondary capture" onClick={photo} title="Save rendered frame"><Camera/>Photo</button><button className={'secondary capture '+(recording?'recording':'')} onClick={record} title="Record rendered output"><Video/>{recording?'Stop':'Record'}</button><label className="secondary upload"><ImagePlus/>Replace photo<input type="file" accept="image/*" onChange={upload}/></label><span className="hint">Rendered media is created locally.</span></div></section><SignalPanel state={state} demo={demo}/></div>
 <div className={'camera-float '+(cameraSmall?'minimized':'')}><div className="cam-head"><span><Camera/>DRIVER CAMERA</span><div><b>{state.fps||'—'} FPS</b><button onClick={()=>setCameraSmall(!cameraSmall)}>{cameraSmall?<MonitorUp/>:<Minimize2/>}</button></div></div><div className="video-box"><video ref={videoRef} muted playsInline style={{transform:prefs.mirror?'scaleX(-1)':'none'}}/><MeshOverlay state={state} show={prefs.mesh}/>{!state.running&&<span>Camera is off</span>}</div>{cameraSmall&&<span className="processing-dot">Processing at full speed</span>}</div>
 </main>}

function Range({label,value,onChange,min=0,max=150,suffix='%'}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;suffix?:string}){return <label className="range"><span>{label}<b>{value}{suffix}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)}/></label>}
function SettingsDrawer({open,close,prefs,setPrefs}:{open:boolean;close:()=>void;prefs:Prefs;setPrefs:(p:Prefs)=>void}){const up=(k:keyof Prefs,v:Prefs[keyof Prefs])=>setPrefs({...prefs,[k]:v});return <><div className={'drawer-back '+(open?'show':'')} onClick={close}/><aside className={'drawer '+(open?'show':'')}><div className="drawer-head"><div><span>STUDIO SETTINGS</span><h2>Fine-tune your mirror</h2></div><button className="icon-btn" onClick={close}><X/></button></div><div className="settings-body"><section><h3><Activity/>Motion retargeting</h3><Range label="Expression sensitivity" value={prefs.sensitivity} onChange={v=>up('sensitivity',v)} max={100}/><Range label="Temporal smoothing" value={prefs.smoothing} onChange={v=>up('smoothing',v)} max={100}/><Range label="Head pose" value={prefs.pose} onChange={v=>up('pose',v)} max={100}/><Range label="Mouth movement" value={prefs.mouth} onChange={v=>up('mouth',v)} max={100}/></section><section><h3><MonitorUp/>Advanced display</h3><Range label="Brightness" value={prefs.brightness} onChange={v=>up('brightness',v)}/><Range label="Contrast" value={prefs.contrast} onChange={v=>up('contrast',v)}/><Range label="Saturation" value={prefs.saturation} onChange={v=>up('saturation',v)}/><label className="select-row"><span>Render quality<small>Higher quality uses more GPU</small></span><select value={prefs.quality} onChange={e=>up('quality',e.target.value)}><option>Performance</option><option>High</option><option>Ultra</option></select></label></section><section><h3><Gauge/>View & performance</h3>{([['mesh','Landmark mesh','Draw live tracking points'],['mirror','Mirror driver camera','Match your natural mirror view'],['identity','Identity lock','Only deform original portrait pixels'],['reduceMotion','Freeze portrait motion','Keep tracking active in background']] as const).map(([k,a,b])=><label className="toggle" key={k}><span>{a}<small>{b}</small></span><input type="checkbox" checked={prefs[k] as boolean} onChange={e=>up(k,e.target.checked)}/><i/></label>)}</section></div><div className="drawer-foot"><button className="secondary" onClick={()=>setPrefs(defaults)}>Reset defaults</button><button className="primary" onClick={close}><Check/>Apply settings</button></div></aside></>}

export default function App(){const route=useRoute();const engine=useFaceEngine();const [settings,setSettings]=useState(false);const [prefs,setPrefs]=useState<Prefs>(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem('fm-prefs-v2')||'{}')}}catch{return defaults}});useEffect(()=>localStorage.setItem('fm-prefs-v2',JSON.stringify(prefs)),[prefs]);const demo=useMemo(()=>getDemo(route),[route]);return <><Header state={engine.state} onSettings={()=>setSettings(true)}/>{route==='home'?<Home open={d=>go(d.slug)}/>:<Workspace demo={demo} state={engine.state} videoRef={engine.videoRef} start={engine.start} stop={engine.stop} detectStill={engine.detectStill} prefs={prefs} setPrefs={setPrefs} onSettings={()=>setSettings(true)}/>}<SettingsDrawer open={settings} close={()=>setSettings(false)} prefs={prefs} setPrefs={setPrefs}/></>}
