import { ScanFace, Sparkles, AudioLines, Box, WandSparkles, Waves, Smile, Aperture } from 'lucide-react';

export type Demo = {
  slug: string; title: string; eyebrow: string; description: string; category: string;
  accent: string; icon: typeof ScanFace; capabilities: string[]; note?: string;
};

export const demos: Demo[] = [
  { slug:'mediapipe-mesh', title:'MediaPipe Face Mesh', eyebrow:'478 landmarks · live', description:'High-density 3D landmarks, blendshapes, and a facial transform matrix running locally in your browser.', category:'Landmark detection', accent:'#a78bfa', icon:ScanFace, capabilities:['478-point topology','52 blendshapes','GPU / CPU inference'] },
  { slug:'dlib-68', title:'Classic 68-Point Map', eyebrow:'iBUG topology', description:'A live 68-point visualization mapped from the dense MediaPipe mesh to the familiar dlib/iBUG regions.', category:'Landmark detection', accent:'#38bdf8', icon:Aperture, capabilities:['Jawline','Brows & nose','Eyes & lips'], note:'Visualization uses a 68-point subset of MediaPipe landmarks; dlib itself is not shipped to the browser.' },
  { slug:'openface-au', title:'Action Unit Lab', eyebrow:'FACS-inspired · live', description:'Inspect expression signals for brows, eyes, cheeks, jaw, and lips as animated meters.', category:'Landmark detection', accent:'#2dd4bf', icon:Waves, capabilities:['Live expression meters','Confidence readout','Signal smoothing'], note:'Signals are MediaPipe blendshapes with FACS-inspired labels, not an OpenFace diagnostic result.' },
  { slug:'fan-alignment', title:'Face Alignment Network', eyebrow:'2D / 3D alignment view', description:'Explore normalized geometry, depth cues, symmetry axes, and pose-stable alignment.', category:'Landmark detection', accent:'#f472b6', icon:Box, capabilities:['Depth color map','Alignment guides','Pose normalization'], note:'Interactive browser analogue powered by MediaPipe geometry.' },

  { slug:'fomm', title:'First-Order Motion', eyebrow:'keypoint motion', description:'Drive a still portrait with sparse facial motion and occlusion-aware region compositing.', category:'Portrait motion', accent:'#fb7185', icon:Sparkles, capabilities:['Source identity pixels','Live keypoint motion','Region compositing'] },
  { slug:'tps', title:'Thin Plate Spline', eyebrow:'expressive warp', description:'A higher-flexibility local warp view for eyebrows, eyes, mouth, jaw, and head pose.', category:'Portrait motion', accent:'#f97316', icon:WandSparkles, capabilities:['Local deformation','Large expression range','Smooth falloff'] },
  { slug:'face-vid2vid', title:'Face Vid2Vid', eyebrow:'pose + expression', description:'Separate head-pose and expression controls while reenacting a static portrait.', category:'Portrait motion', accent:'#facc15', icon:Box, capabilities:['Pose decomposition','Expression transfer','Free-view preview'] },
  { slug:'megaportraits', title:'MegaPortraits', eyebrow:'avatar detail', description:'Identity-preserving portrait animation with enhanced detail and a clean comparison view.', category:'Portrait motion', accent:'#a3e635', icon:Sparkles, capabilities:['Detail emphasis','Identity lock','Cross-driver controls'] },
  { slug:'liveportrait', title:'LivePortrait', eyebrow:'stitching + retargeting', description:'The flagship instant mirror: retarget eyes, mouth, jaw, and pose from webcam to photo.', category:'Portrait motion', accent:'#22c55e', icon:ScanFace, capabilities:['Live retargeting','Stitching controls','Webcam minimizer'] },

  { slug:'flame-mouth', title:'FLAME Oral Rig', eyebrow:'parametric view', description:'Visualize jaw, lip, teeth, and tongue parameters with an explicit oral-cavity overlay.', category:'Mouth studio', accent:'#14b8a6', icon:Smile, capabilities:['Jaw parameter','Lip contours','Oral cavity guides'] },
  { slug:'emoca-deca', title:'EMOCA + DECA Fitting', eyebrow:'3D face parameters', description:'Inspect expression, shape, detail, and pose channels used to fit parametric faces to portraits.', category:'Mouth studio', accent:'#10b981', icon:Box, capabilities:['3DMM channels','Detail map','Expression fit'], note:'Live parameter visualization; full PyTorch EMOCA/DECA fitting requires a server GPU.' },
  { slug:'explicit-teeth', title:'Explicit Teeth Model', eyebrow:'procedural oral geometry', description:'Render separate shaded teeth, tooth divisions, cavity depth, tongue geometry, and wet highlights.', category:'Mouth studio', accent:'#34d399', icon:Smile, capabilities:['Rigid dental layer','Tongue shading','PBR-style highlights'] },
  { slug:'neural-mouth', title:'Neural Mouth Renderer', eyebrow:'region synthesis preview', description:'Isolate the mouth ROI, inspect its mask, and preview context-aware compositing.', category:'Mouth studio', accent:'#06b6d4', icon:Aperture, capabilities:['Mouth ROI','Feathered mask','Context composite'] },
  { slug:'mouth-inpainting', title:'Conditional Mouth Inpainting', eyebrow:'identity + context mask', description:'Explore a conditional lower-face mask driven by expression, source identity, and surrounding face context.', category:'Mouth studio', accent:'#22d3ee', icon:WandSparkles, capabilities:['Conditional mask','Identity context','Feathered blend'], note:'The browser uses deterministic compositing; no remote generative service receives your face.' },
  { slug:'viseme-alignment', title:'Phoneme & Viseme Aligner', eyebrow:'forced-alignment pipeline', description:'Explore the phoneme-to-viseme stage used ahead of jaw, lip, and tongue parameter estimation.', category:'Audio & speech', accent:'#0284c7', icon:AudioLines, capabilities:['Phoneme timeline','Viseme classes','Tongue cues'], note:'Interactive viseme workspace inspired by forced alignment; Montreal Forced Aligner itself is a desktop/server tool.' },
  { slug:'wav2lip', title:'Wav2Lip Workspace', eyebrow:'audio-reactive visemes', description:'Use microphone energy to drive viseme-style mouth motion while preserving the source portrait.', category:'Audio & speech', accent:'#0ea5e9', icon:AudioLines, capabilities:['Microphone input','Viseme monitor','Lower-face preview'], note:'This lightweight demo is audio-reactive; it does not bundle the multi-gigabyte Wav2Lip inference stack.' },
  { slug:'musetalk', title:'MuseTalk Workspace', eyebrow:'latent-space lip sync', description:'Inspect a real-time latent mouth-region workflow with source preservation and compositing controls.', category:'Audio & speech', accent:'#2563eb', icon:AudioLines, capabilities:['Latent ROI','Real-time preview','Face blending'], note:'Browser analogue; official MuseTalk GPU inference is not embedded in this static client.' },
  { slug:'sadtalker', title:'SadTalker Workspace', eyebrow:'3DMM expression + pose', description:'Combine live expression coefficients with smooth, independent head motion.', category:'Audio & speech', accent:'#3b82f6', icon:AudioLines, capabilities:['Expression vector','Pose motion','Source preview'] },
  { slug:'video-retalking', title:'VideoReTalking', eyebrow:'three-stage pipeline', description:'Preview canonical alignment, lip retargeting, and enhancement as a staged pipeline.', category:'Audio & speech', accent:'#6366f1', icon:WandSparkles, capabilities:['Canonical face','Lip stage','Enhancement stage'] },
  { slug:'geneface', title:'GeneFace++', eyebrow:'radiance-field view', description:'Inspect a point-field visualization that responds to face pose and mouth motion.', category:'Audio & speech', accent:'#8b5cf6', icon:Box, capabilities:['Neural point field','Pose conditioning','Identity profile'], note:'Interactive visualization—not person-specific NeRF training.' },
  { slug:'aniportrait', title:'AniPortrait', eyebrow:'landmark-guided motion', description:'Animate a portrait with temporally smoothed landmark guidance and motion trails.', category:'Audio & speech', accent:'#d946ef', icon:Waves, capabilities:['Landmark guidance','Temporal smoothing','Motion trails'] },

  { slug:'emo', title:'EMO Diffusion Lab', eyebrow:'pixel-generation concept', description:'Explore a diffusion-inspired denoise timeline over a live-driven portrait result.', category:'Diffusion frontier', accent:'#ec4899', icon:Sparkles, capabilities:['Denoise stages','Audio response','Temporal controls'], note:'Visualization only; EMO weights have not been publicly released for local browser inference.' },
  { slug:'hallo', title:'Hallo / Hallo2', eyebrow:'hierarchical audio', description:'Visualize hierarchical face, lip, and pose control signals in one live workspace.', category:'Diffusion frontier', accent:'#f43f5e', icon:AudioLines, capabilities:['Hierarchical controls','Mask layers','Motion preview'], note:'Browser-native visualization, not the full research checkpoint.' },
  { slug:'vasa', title:'VASA-1 Lab', eyebrow:'holistic face dynamics', description:'A responsive dynamics panel for gaze, pose, emotion, and mouth activity.', category:'Diffusion frontier', accent:'#ef4444', icon:Waves, capabilities:['Holistic dynamics','Gaze vectors','Real-time monitor'], note:'VASA-1 is a research system without a public inference model.' },

  { slug:'pipeline', title:'End-to-End Pipeline', eyebrow:'all stages · one view', description:'See capture, landmarks, retargeting, mouth compositing, enhancement, and output timing.', category:'Pipeline tools', accent:'#fb923c', icon:WandSparkles, capabilities:['Stage timings','Live status','Output monitor'] },
  { slug:'face-enhancement', title:'Face Enhancement Suite', eyebrow:'GFPGAN · CodeFormer · RestoreFormer', description:'Compare restoration concepts, fidelity controls, detail recovery, and temporally stable enhancement.', category:'Pipeline tools', accent:'#f97316', icon:Sparkles, capabilities:['Detail recovery','Fidelity control','Temporal guard'], note:'Non-destructive display preview; named server-grade restoration checkpoints are not executed in-browser.' },
  { slug:'seamless-composite', title:'Seamless Compositing', eyebrow:'Poisson + learned blending', description:'Inspect mask feathering, color matching, mouth-corner shadows, and boundary continuity.', category:'Pipeline tools', accent:'#ea580c', icon:Aperture, capabilities:['Poisson concept','Color transfer','Boundary mask'] },
  { slug:'teeth-lab', title:'Teeth & Tongue Lab', eyebrow:'oral detail controls', description:'Tune tooth visibility, tongue response, mouth shadows, moisture highlights, and feathering.', category:'Pipeline tools', accent:'#fbbf24', icon:Smile, capabilities:['Oral detail guides','Phoneme response','Specular controls'] },
];

export const categories = [...new Set(demos.map(d => d.category))];
export const getDemo = (slug: string) => demos.find(d => d.slug === slug) || demos[0];
