import { useCallback, useEffect, useRef, useState } from 'react';
export type NeuralState={status:'idle'|'loading'|'ready'|'running'|'error'|'unsupported';progress:number;detail:string;inferenceMs:number;frame:ImageBitmap|null};
export function useLivePortrait(videoRef:React.RefObject<HTMLVideoElement>){
 const worker=useRef<Worker|null>(null),active=useRef(false),sourceReady=useRef(false),sourceUrl=useRef(''),frameRef=useRef<ImageBitmap|null>(null);
 const [state,setState]=useState<NeuralState>({status:'idle',progress:0,detail:'Real LivePortrait · WebGPU',inferenceMs:0,frame:null});
 const requestFrame=useCallback(async()=>{const v=videoRef.current;if(!active.current||!sourceReady.current||!worker.current||!v||v.readyState<2)return;try{const size=Math.min(v.videoWidth,v.videoHeight),sx=(v.videoWidth-size)/2,sy=Math.max(0,(v.videoHeight-size)/2-size*.08);const bitmap=await createImageBitmap(v,sx,sy,size,size,{resizeWidth:256,resizeHeight:256});worker.current.postMessage({type:'frame',bitmap},[bitmap])}catch(e){setState(s=>({...s,status:'error',detail:e instanceof Error?e.message:String(e)}))}},[videoRef]);
 const ensure=useCallback(()=>{if(worker.current)return worker.current;if(!('gpu' in navigator)){setState(s=>({...s,status:'unsupported',detail:'WebGPU unavailable — use current Chrome or Edge with hardware acceleration'}));return null}const w=new Worker(new URL('./workers/liveportrait.worker.ts',import.meta.url),{type:'module'});w.onmessage=e=>{if(e.data.type==='status')setState(s=>({...s,status:e.data.progress===100?'ready':'loading',progress:e.data.progress,detail:`${e.data.stage}${e.data.detail?' · '+e.data.detail:''}`}));else if(e.data.type==='sourceReady'){sourceReady.current=true;setState(s=>({...s,status:'ready',progress:100,detail:'LivePortrait identity encoded'}));if(active.current)requestFrame()}else if(e.data.type==='frame'){const old=frameRef.current;frameRef.current=e.data.frame;setState(s=>({...s,status:'running',frame:e.data.frame,inferenceMs:e.data.ms,detail:`Neural render · ${e.data.ms} ms`}));setTimeout(()=>old?.close(),100);if(active.current)requestAnimationFrame(requestFrame)}else if(e.data.type==='error')setState(s=>({...s,status:'error',detail:e.data.message}))};worker.current=w;return w},[requestFrame]);
 const loadSource=useCallback(async(src:string)=>{const w=ensure();if(!w||sourceUrl.current===src&&sourceReady.current)return;sourceUrl.current=src;sourceReady.current=false;setState(s=>({...s,status:'loading',progress:1,detail:'Preparing neural model download'}));const blob=await fetch(src).then(r=>r.blob()),bitmap=await createImageBitmap(blob);w.postMessage({type:'source',bitmap},[bitmap])},[ensure]);
 const start=useCallback(async(src:string)=>{active.current=true;await loadSource(src);if(sourceReady.current)requestFrame()},[loadSource,requestFrame]);
 const stop=useCallback(()=>{active.current=false;setState(s=>({...s,status:s.frame?'ready':'idle'}))},[]);
 useEffect(()=>()=>{active.current=false;worker.current?.terminate();frameRef.current?.close()},[]);
 return {state,start,stop,loadSource};
}
